# Generated by Django 4.2.15 on 2024-09-03 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='user')),
            ],
        ),
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=150, verbose_name='label')),
                ('content', models.CharField(blank=True, max_length=10000, null=True, verbose_name='content')),
                ('user', models.ForeignKey(max_length=32, on_delete=django.db.models.deletion.CASCADE, to='work_space.users')),
            ],
        ),
    ]
