# Generated by Django 4.2.15 on 2024-09-03 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work_space', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='notes',
            table='notes',
        ),
        migrations.AlterModelTable(
            name='users',
            table='users',
        ),
    ]
