# Generated by Django 4.2.15 on 2024-09-03 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('work_space', '0002_alter_notes_table_alter_users_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='user',
            field=models.ForeignKey(max_length=32, on_delete=django.db.models.deletion.CASCADE, to='work_space.users', verbose_name='user'),
        ),
    ]
