# Generated by Django 4.2.15 on 2024-09-04 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work_space', '0003_alter_notes_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notes',
            old_name='user',
            new_name='user_id',
        ),
    ]
