# Generated by Django 4.2.15 on 2024-09-06 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_space', '0004_rename_user_notes_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='content',
            field=models.CharField(blank=True, default='', max_length=10000, null=True, verbose_name='content'),
        ),
    ]
