# Generated by Django 4.2.15 on 2024-09-14 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work_space', '0005_alter_notes_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notes',
            old_name='user_id',
            new_name='user',
        ),
    ]
